name: OR Condition Demo
on: push
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run for Gagan or GaganMehra-MSFT
        if: github.actor == 'Gagan' || github.actor == 'GaganMehra'
        run:  echo "Running on main branch by Gagan"
    
